module.exports = {
        searchcpu: 'ryzen 3600x',
        searchcpucooler: 'cooler',
        searchmotherboard: 'B450',
        searchram: 'corsair',
        searchstorage: 'samsung',
        searchgpu: 'EVGA 6',
        searchcase: 'NZXT',
        searchpower: 'CXM',
        searchos: 'Windows',
        cpu: 'AMD Ryzen 5 3600X 3.8 GHz 6-Core Processor',
        cpucooler: 'Cooler Master Hyper 212 EVO 82.9 CFM Sleeve Bearing CPU Cooler',
        motherboard: 'MSI B450 TOMAHAWK MAX ATX AM4 Motherboard',
        ram: 'Corsair Vengeance RGB Pro 16 GB (2 x 8 GB) DDR4-3000 CL16 Memory',
        storage: 'Samsung 860 Evo 1 TB 2.5" Solid State Drive',
        gpu: 'EVGA GeForce GTX 1060 6GB 6 GB SC GAMING Video Card',
        case: 'NZXT H510 ATX Mid Tower Case',
        power: 'Corsair CXM 650 W 80+ Bronze Certified Semi-modular ATX Power Supply',
        os: 'Microsoft Windows 10 Pro OEM 64-bit',
        searchcpu1: 'i9',
        searchcpucooler1: 'corsair',
        searchmotherboard1: 'asus prime',
        searchram1: 'cor',
        searchstorage1: '4 tb',
        searchgpu1: 'asus',
        searchcase1: 'NZXT',
        searchpower1: 'RMx',
        searchos1: 'Windows',
        cpu1: 'Intel Core i9-9900K 3.6 GHz 8-Core Processor',
        cpucooler1: 'Corsair H100i RGB PLATINUM 75 CFM Liquid CPU Cooler',
        motherboard1: 'Asus PRIME Z390-A ATX LGA1151 Motherboard',
        ram1: 'Corsair Vengeance RGB Pro 16 GB (2 x 8 GB) DDR4-3000 CL16 Memory',
        storage1: 'Samsung 860 Pro 4 TB 2.5" Solid State Drive',
        gpu1: 'Asus GeForce RTX 2080 Ti 11 GB ROG Strix Gaming OC Video Card',
        case1: 'NZXT H510 Elite ATX Mid Tower Case',
        power1: 'Corsair RMx (2018) 850 W 80+ Gold Certified Fully Modular ATX Power Supply',
        os1: 'Microsoft Windows 10 Pro OEM 64-bit',
        editOS: 'Microsoft Windows 10 Pro OEM 64-bit'
    }
